version: "3"
services:
  backend:
    build:
      context: ./backend
    container_name: mern-backend
    ports:
      - "5001:5000"
    env_file:
      - ./backend/.env

  frontend:
    build:
      context: ./frontend
    container_name: mern-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
